import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { LoginComponent } from './components/auth/login.component';
import { RegisterComponent } from './components/auth/register.component';
import { BikeDetailComponent } from './components/bikes/bike-detail.component';
import { BikeListComponent } from './components/bikes/bike-list.component';
import { BikeRegisterComponent } from './components/bikes/bike-register.component';
import { BikeTransferComponent } from './components/bikes/bike-transfer.component';
import { AuthGuard } from './guards/auth.guard';
import { ManufacturerManagementComponent } from './components/admin/manufacturer-management.component';
import { BrandManagementComponent } from './components/admin/brand-management.component';
